x1 = int(input("please enter the Value X1:  "))
x2 = int(input("please enter the Value X2:  "))
y1 = int(input("please enter the Value Y1:  "))
y2 = int(input("please enter the Value Y2:  "))
d = ((x2-x1)**2 + (y2-y1)**2)**(1/2)
print (d)