print( "Enter the input below")
name = input("user's name?: ")
age = input("User's age:  ")
city = input( "user's city: ")
college = input( "user's college: ")
job = input( "user's Profession: ")
pet = input( "user's pet name: ")
print( "There once was a person", name, "Who lived in", city, "At the Age of", age, name, "went to college at", college, name, "graduated and work as a", job, "Then", name, "addopted an animal named", pet, "They both lived happily ever after")
